### ISSUE TITLE
Google Colab Notebook (Enhancement)

### ISSUE THREAD

**Issue by zanderbush** [dldk-gael/lm-heuristic#2]
Could you please upload a Google Colab Notebook or Juypter Notebook? It would be very much appreciate for those like me who are new to NLP.

**Comment by dldk-gael** [comment]
Hello @zanderbush and sorry for the answer delay. 
In this repo, I am making lot of experiments / tests / research as part of a master thesis. It is not stable and code will often change / break compatibility with previous version. 
I made this repo public only because it allows me to clone it very quickly from a collab notebook ;) 

So for now, I don't plan to make a notebook but why not at the end of my master thesis ...

**Comment by zanderbush** [comment]
No worries. I totally understand. Thank you for letting me know.
